#!/usr/bin/env python

# ros
from manipulation_809e import manipulation_class
import rospy


if __name__ == '__main__':
    manipulation = manipulation_class.Manipulation(ns='/ariac/kitting')
    manipulation.main()
    rospy.loginfo("I am here")
    # manipulation.test_arm_base()
